name: ${name}
main: ${main}
version: ${version}
author: ${author}
api-version: 1.17

depend:
  - packetevents

softdepend:
  - PlaceholderAPI
  - TAB
  - SkinsRestorer

commands:
  nametags-reload:
    description: Reload the config
    permission: nametags.command.reload
  nametags-toggle:
    description: Toggle visibility of player nametags
    permission: nametags.command.toggle
    usage: /nametags-toggle [on/off] [player]

permissions:
  nametags.command.reload:
    description: Allows reloading the plugin configuration
    default: op
  nametags.command.toggle:
    description: Allows toggling nametag visibility for yourself
    default: true
  nametags.command.toggle.others:
    description: Allows toggling nametag visibility for other players
    default: op
